import React, { useState } from "react";
import BookList from "../../components/pages/Admin/BookList";
import LibraryManagementHeader from "../../components/pages/Admin/LibraryManagementHeader";
import ShowEntriesDropdown from "../../components/pages/Admin/ShowEntriesDropdown";
const jsonData = {
  headers: ["TITLE", "AUTHOR", "ISBN", "CATEGORY", "AVAILABILTY", "ACTION"],
  data: [
    {
      id: 1,
      title: "Book 1",
      author: "Author 1",
      isbn: "ISBN 12345",
      category: "Fiction",
      available: true,
    },
    {
      id: 2,
      title: "Book 2",
      author: "Author 2",
      isbn: "ISBN 67890",
      category: "Non-Fiction",
      available: false,
    },
    {
      id: 3,
      title: "Book 3",
      author: "Author 3",
      isbn: "ISBN 54321",
      category: "Science",
      available: true,
    },
    {
      id: 1,
      title: "Book 1",
      author: "Author 1",
      isbn: "ISBN 12345",
      category: "Fiction",
      available: true,
    },
    {
      id: 2,
      title: "Book 2",
      author: "Author 2",
      isbn: "ISBN 67890",
      category: "Non-Fiction",
      available: false,
    },
    {
      id: 3,
      title: "Book 3",
      author: "Author 3",
      isbn: "ISBN 54321",
      category: "Science",
      available: true,
    },
    {
      id: 1,
      title: "Book 1",
      author: "Author 1",
      isbn: "ISBN 12345",
      category: "Fiction",
      available: true,
    },
    {
      id: 2,
      title: "Book 2",
      author: "Author 2",
      isbn: "ISBN 67890",
      category: "Non-Fiction",
      available: false,
    },
    {
      id: 3,
      title: "Book 3",
      author: "Author 3",
      isbn: "ISBN 54321",
      category: "Science",
      available: true,
    },
    {
      id: 1,
      title: "Book 1",
      author: "Author 1",
      isbn: "ISBN 12345",
      category: "Fiction",
      available: true,
    },
    {
      id: 2,
      title: "Book 2",
      author: "Author 2",
      isbn: "ISBN 67890",
      category: "Non-Fiction",
      available: false,
    },
    {
      id: 3,
      title: "Book 3",
      author: "Author 3",
      isbn: "ISBN 54321",
      category: "Science",
      available: true,
    },
    {
      id: 1,
      title: "Book 1",
      author: "Author 1",
      isbn: "ISBN 12345",
      category: "Fiction",
      available: true,
    },
    {
      id: 2,
      title: "Book 2",
      author: "Author 2",
      isbn: "ISBN 67890",
      category: "Non-Fiction",
      available: false,
    },
    {
      id: 3,
      title: "Book 3",
      author: "Author 3",
      isbn: "ISBN 54321",
      category: "Science",
      available: true,
    },
    {
      id: 1,
      title: "Book 1",
      author: "Author 1",
      isbn: "ISBN 12345",
      category: "Fiction",
      available: true,
    },
    {
      id: 2,
      title: "Book 2",
      author: "Author 2",
      isbn: "ISBN 67890",
      category: "Non-Fiction",
      available: false,
    },
    {
      id: 3,
      title: "Book 3",
      author: "Author 3",
      isbn: "ISBN 54321",
      category: "Science",
      available: true,
    },
    {
      id: 1,
      title: "Book 1",
      author: "Author 1",
      isbn: "ISBN 12345",
      category: "Fiction",
      available: true,
    },
    {
      id: 2,
      title: "Book 2",
      author: "Author 2",
      isbn: "ISBN 67890",
      category: "Non-Fiction",
      available: false,
    },
    {
      id: 3,
      title: "Book 3",
      author: "Author 3",
      isbn: "ISBN 54321",
      category: "Science",
      available: true,
    },
    {
      id: 1,
      title: "Book 1",
      author: "Author 1",
      isbn: "ISBN 12345",
      category: "Fiction",
      available: true,
    },
    {
      id: 2,
      title: "Book 2",
      author: "Author 2",
      isbn: "ISBN 67890",
      category: "Non-Fiction",
      available: false,
    },
    {
      id: 3,
      title: "Book 3",
      author: "Author 3",
      isbn: "ISBN 54321",
      category: "Science",
      available: true,
    },
    {
      id: 1,
      title: "Book 1",
      author: "Author 1",
      isbn: "ISBN 12345",
      category: "Fiction",
      available: true,
    },
    {
      id: 2,
      title: "Book 2",
      author: "Author 2",
      isbn: "ISBN 67890",
      category: "Non-Fiction",
      available: false,
    },
    {
      id: 3,
      title: "Book 3",
      author: "Author 3",
      isbn: "ISBN 54321",
      category: "Science",
      available: true,
    },
    {
      id: 1,
      title: "Book 1",
      author: "Author 1",
      isbn: "ISBN 12345",
      category: "Fiction",
      available: true,
    },
    {
      id: 2,
      title: "Book 2",
      author: "Author 2",
      isbn: "ISBN 67890",
      category: "Non-Fiction",
      available: false,
    },
    {
      id: 3,
      title: "Book 3",
      author: "Author 3",
      isbn: "ISBN 54321",
      category: "Science",
      available: true,
    },
    {
      id: 1,
      title: "Book 1",
      author: "Author 1",
      isbn: "ISBN 12345",
      category: "Fiction",
      available: true,
    },
    {
      id: 2,
      title: "Book 2",
      author: "Author 2",
      isbn: "ISBN 67890",
      category: "Non-Fiction",
      available: false,
    },
    {
      id: 3,
      title: "Book 3",
      author: "Author 3",
      isbn: "ISBN 54321",
      category: "Science",
      available: true,
    },
    {
      id: 1,
      title: "Book 1",
      author: "Author 1",
      isbn: "ISBN 12345",
      category: "Fiction",
      available: true,
    },
    {
      id: 2,
      title: "Book 2",
      author: "Author 2",
      isbn: "ISBN 67890",
      category: "Non-Fiction",
      available: false,
    },
    {
      id: 3,
      title: "Book 3",
      author: "Author 3",
      isbn: "ISBN 54321",
      category: "Science",
      available: true,
    },
    {
      id: 1,
      title: "Book 1",
      author: "Author 1",
      isbn: "ISBN 12345",
      category: "Fiction",
      available: true,
    },
    {
      id: 2,
      title: "Book 2",
      author: "Author 2",
      isbn: "ISBN 67890",
      category: "Non-Fiction",
      available: false,
    },
    {
      id: 3,
      title: "Book 3",
      author: "Author 3",
      isbn: "ISBN 54321",
      category: "Science",
      available: true,
    },
    {
      id: 1,
      title: "Book 1",
      author: "Author 1",
      isbn: "ISBN 12345",
      category: "Fiction",
      available: true,
    },
    {
      id: 2,
      title: "Book 2",
      author: "Author 2",
      isbn: "ISBN 67890",
      category: "Non-Fiction",
      available: false,
    },
    {
      id: 3,
      title: "Book 3",
      author: "Author 3",
      isbn: "ISBN 54321",
      category: "Science",
      available: true,
    },
    {
      id: 1,
      title: "Book 1",
      author: "Author 1",
      isbn: "ISBN 12345",
      category: "Fiction",
      available: true,
    },
    {
      id: 2,
      title: "Book 2",
      author: "Author 2",
      isbn: "ISBN 67890",
      category: "Non-Fiction",
      available: false,
    },
    {
      id: 3,
      title: "Book 3",
      author: "Author 3",
      isbn: "ISBN 54321",
      category: "Science",
      available: true,
    },
    {
      id: 1,
      title: "Book 1",
      author: "Author 1",
      isbn: "ISBN 12345",
      category: "Fiction",
      available: true,
    },
    {
      id: 2,
      title: "Book 2",
      author: "Author 2",
      isbn: "ISBN 67890",
      category: "Non-Fiction",
      available: false,
    },
    {
      id: 3,
      title: "Book 3",
      author: "Author 3",
      isbn: "ISBN 54321",
      category: "Science",
      available: true,
    },
    {
      id: 1,
      title: "Book 1",
      author: "Author 1",
      isbn: "ISBN 12345",
      category: "Fiction",
      available: true,
    },
    {
      id: 2,
      title: "Book 2",
      author: "Author 2",
      isbn: "ISBN 67890",
      category: "Non-Fiction",
      available: false,
    },
    {
      id: 3,
      title: "Book 3",
      author: "Author 3",
      isbn: "ISBN 54321",
      category: "Science",
      available: true,
    },
    {
      id: 1,
      title: "Book 1",
      author: "Author 1",
      isbn: "ISBN 12345",
      category: "Fiction",
      available: true,
    },
    {
      id: 2,
      title: "Book 2",
      author: "Author 2",
      isbn: "ISBN 67890",
      category: "Non-Fiction",
      available: false,
    },
    {
      id: 3,
      title: "Book 3",
      author: "Author 3",
      isbn: "ISBN 54321",
      category: "Science",
      available: true,
    },
    {
      id: 1,
      title: "Book 1",
      author: "Author 1",
      isbn: "ISBN 12345",
      category: "Fiction",
      available: true,
    },
    {
      id: 2,
      title: "Book 2",
      author: "Author 2",
      isbn: "ISBN 67890",
      category: "Non-Fiction",
      available: false,
    },
    {
      id: 3,
      title: "Book 3",
      author: "Author 3",
      isbn: "ISBN 54321",
      category: "Science",
      available: true,
    },
    {
      id: 1,
      title: "Book 1",
      author: "Author 1",
      isbn: "ISBN 12345",
      category: "Fiction",
      available: true,
    },
    {
      id: 2,
      title: "Book 2",
      author: "Author 2",
      isbn: "ISBN 67890",
      category: "Non-Fiction",
      available: false,
    },
    {
      id: 3,
      title: "Book 3",
      author: "Author 3",
      isbn: "ISBN 54321",
      category: "Science",
      available: true,
    },
  ],
};

export default function LibraryView() {
  const [entries, setEntries] = useState(5);
  const headers = jsonData.headers;
  const data = jsonData.data;
  return (
    <>
      <LibraryManagementHeader>
       <ShowEntriesDropdown entries={entries} setEntries={setEntries} />
       <BookList headers={headers} data={data} entries={entries} />
      </LibraryManagementHeader>
    </>
  );
}
